listen = "0.0.0.0:8080"
timeout_secs = 5
max_outbound_concurrency = 32
mode = "simple"
# Operation mode: "simple" forwards only the first metric; "multi" splits by metric and merges results.
# mode = "multi"

[[backends]]
pattern = "^project_102__ilens\\.live_data\\.raw$"
url = "http://project-102-kairosdb.ilens-infra:80"


[[backends]]
pattern = "^project_103__ilens\\.live_data\\.raw$"
url = "http://project-103-kairosdb.ilens-infra:80"

[[backends]]
pattern = "^project_104__ilens\\.live_data\\.raw$"
url = "http://project-104-kairosdb.ilens-infra:80"
